version: '3.8'
services:
  # mosquitto:
  #     image: eclipse-mosquitto:2
  #     container_name: mosquitto
  #     restart: unless-stopped
  #     ports:
  #       - "1883:1883"
  #     volumes:
  #       - ./mosquitto/config:/mosquitto/config
  #       - ./mosquitto/data:/mosquitto/data
  #       - ./mosquitto/log:/mosquitto/log
  app:
    build: .
    ports:
      - "3005:3001"
    environment:
      - PORT=3001
    # depends_on:
    #   - mosquitto
    restart: unless-stopped
